### ISSUE TITLE
Crash in RRT Sometimes

### ISSUE THREAD

**Issue by mirisr** [BYU-PCCL/mindreader#6]
Might be the previous fixed I have done here.

```/Users/Iris/Documents/Repos/mindreader/my_rrt.py:153: RuntimeWarning: invalid value encountered in divide
  ndiff = (scale * STEP_SIZE) * ndiff / np.sqrt( np.sum( ndiff*ndiff ) )
/Users/Iris/Documents/Repos/mindreader/my_rrt.py:30: RuntimeWarning: invalid value encountered in greater_equal
  did_intersect = (u_a >= 0) & (u_a <= 1) & (u_b >= 0) & (u_b <= 1)
/Users/Iris/Documents/Repos/mindreader/my_rrt.py:30: RuntimeWarning: invalid value encountered in less_equal
  did_intersect = (u_a >= 0) & (u_a <= 1) & (u_b >= 0) & (u_b <= 1)
Traceback (most recent call last):
  File "runner.py", line 138, in <module>
    R.run(None)
  File "runner.py", line 48, in run
    enf_plan = self.plan_path(enf_start, enf_goal)
  File "runner.py", line 27, in <lambda>
    self.plan_path = lambda start_loc, goal_loc: planner.run_rrt_opt( start_loc, goal_loc, rx1,ry1,rx2,ry2 )```

**Comment by mirisr** [comment]
Reference planner.py (its main function) to set up the RRT and run.
Andrew, here is the original paper (if you think it will help)
http://msl.cs.uiuc.edu/~lavalle/papers/Lav98c.pdf

**Comment by andrewnc** [comment]
In my_rtt.py > line_intersect() calculates a denominator vector that often has 0 values. This denominator is used to calculate u_a and u_b values that become NaN. There are a few options to fix this:
- Try-Catch
- Manually Edit 0 values
- Implement a different intersect method that has no divide by 0 possibilities

**Comment by mirisr** [comment]
@andrewnc: you should look into why the RRT algorithm causes that. That function is pretty sound. There's something else before that really is the issue.

**Comment by andrewnc** [comment]
It happens when two lines are parallel, I honestly think it's a shortcoming of the fast line intersect algorithm that needs to be addressed there.

**Comment by mirisr** [comment]
Since we aren't working with the heat map anymore... and something I had changed caused a break in the RRT a while back, I'm reverting to David's old rrt. It still has the same problem, but he handles the problem quicker.

**Comment by mirisr** [comment]
David's rrt is broken, it passes obstacles. Reverting back to mine, but making it take larger steps. David's code had larger step sizes than mine.
